import {useMemo,useState} from 'react';
import {Activity,FileClock} from 'lucide-react';
import {useApp} from '../context/AppContext';
import {PageHeader,Empty,ExportButton} from '../components/common';

const actionText={RECEIVE:'RECEIVE_STOCK',ISSUE:'ISSUE_STOCK',TRANSFER_IN:'TRANSFER_IN',TRANSFER_OUT:'TRANSFER_OUT',OPENING_BALANCE:'OPENING_BALANCE',EDIT:'CHANGE_REQUEST_EDIT',DELETE:'CHANGE_REQUEST_DELETE'};
export default function AuditLogPage(){
 const {movements,auditLogs,currentUser}=useApp();const [search,setSearch]=useState(''),[action,setAction]=useState('');
 const activities=useMemo(()=>{
  const movementRows=movements.map(item=>({id:`MOV-${item.id}`,createdAt:item.createdAt||`${item.transactionDate}T${item.transactionTime}`,username:item.userName||'ผู้ดูแลระบบ',role:'Admin',branch:item.warehouseGroup||item.sourceWarehouse||'—',action:actionText[item.transactionType]||item.transactionType,targetType:'stock_movement',targetId:item.documentNo,detail:`${item.productCode} · ${item.productName}`,ipAddress:item.ipAddress||'ข้อมูลเดิม'}));
  const changeRows=auditLogs.flatMap(log=>{const request={id:`REQ-${log.id}`,createdAt:log.createdAt,username:log.requestedBy||log.approvedBy||'ผู้ดูแลระบบ',role:'Admin',branch:log.warehouseGroup||'—',action:actionText[log.action],targetType:'change_request',targetId:log.documentNo,detail:log.reason,ipAddress:log.ipAddress||'ข้อมูลเดิม'};const approval=log.approvedAt?{...request,id:`APR-${log.id}`,createdAt:log.approvedAt,username:log.approvedBy||currentUser.name,role:log.approvedRole||currentUser.roleLabel,action:log.status==='APPROVED'?'APPROVE_CHANGE':'REJECT_CHANGE'}:null;return approval?[request,approval]:[request]});
  return [...changeRows,...movementRows].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));
 },[movements,auditLogs,currentUser]);
 const actions=[...new Set(activities.map(row=>row.action))];const rows=activities.filter(row=>(!action||row.action===action)&&(!search||`${row.username} ${row.role} ${row.branch} ${row.action} ${row.targetType} ${row.targetId} ${row.detail}`.toLowerCase().includes(search.toLowerCase())));
 return <><PageHeader title="Audit Log" subtitle="ประวัติการใช้งานและกิจกรรมสำคัญภายในระบบคลังสินค้า" actions={<ExportButton rows={rows} name="CSP-audit-log"/>}/><div className="card filters"><label>ค้นหา<input value={search} onChange={event=>setSearch(event.target.value)} placeholder="ผู้ใช้งาน / Action / เอกสาร / สินค้า"/></label><label>Action<select value={action} onChange={event=>setAction(event.target.value)}><option value="">ทั้งหมด</option>{actions.map(value=><option key={value}>{value}</option>)}</select></label><button className="btn ghost" onClick={()=>{setSearch('');setAction('')}}>ล้างค่า</button></div><div className="card audit-card"><div className="audit-title"><div><Activity/><span><b>กิจกรรมในระบบ</b><small>พบข้อมูล {rows.length} รายการ</small></span></div><FileClock/></div><div className="table-wrap audit-scroll"><table className="system-audit-table"><thead><tr><th>วันที่</th><th>เวลา</th><th>Username</th><th>Role</th><th>คลัง</th><th>Action</th><th>Target Type</th><th>Target ID</th><th>รายละเอียด / IP ผู้ใช้งาน</th></tr></thead><tbody>{rows.map(row=>{const date=new Date(row.createdAt);return <tr key={row.id}><td>{date.toLocaleDateString('th-TH')}</td><td>{date.toLocaleTimeString('th-TH')}</td><td><b>{row.username}</b></td><td>{row.role}</td><td>{row.branch}</td><td><span className={`audit-action ${row.action.includes('APPROVE')||row.action.includes('RECEIVE')?'success':row.action.includes('REJECT')||row.action.includes('ISSUE')?'danger':'info'}`}>{row.action}</span></td><td>{row.targetType}</td><td><b>{row.targetId}</b></td><td>{row.detail}<small className="audit-ip">IP: {row.ipAddress}</small></td></tr>})}</tbody></table>{!rows.length&&<Empty/>}</div></div></>;
}
