import {useMemo,useState} from 'react';
import {BarChart3,FileText,Printer,Pencil,Trash2,Clock3,ImagePlus} from 'lucide-react';
import {useApp} from '../context/AppContext';
import {warehouseGroups,movementLabels} from '../data/constants';
import {stockStatus,fmt,printHtml} from '../utils/helpers';
import {PageHeader,ExportButton,StatusBadge,Empty,Modal} from '../components/common';

const reports=['Stock คงเหลือ','รายการรับสินค้า','รายการจ่ายสินค้า','รายการโอนคลัง','Stock Card','ความเคลื่อนไหวสินค้า'];
const emptyFilters={from:'',to:'',group:'',search:''};
const movementTypes={1:['RECEIVE'],2:['ISSUE'],3:['TRANSFER_OUT'],4:null,5:null};
const includesSearch=(item,search)=>!search||`${item.barcode||''} ${item.productCode||''} ${item.productName||''} ${item.documentNo||''}`.toLowerCase().includes(search.toLowerCase());
const inDateRange=(date,from,to)=>(!from||date>=from)&&(!to||date<=to);

export default function ReportsPage(){
  const {products,movements,documents,requestMovementChange}=useApp();
  const [tab,setTab]=useState(0),[draft,setDraft]=useState(emptyFilters),[filters,setFilters]=useState(emptyFilters),[error,setError]=useState(''),[manage,setManage]=useState(null),[quantity,setQuantity]=useState(0),[reason,setReason]=useState(''),[evidence,setEvidence]=useState(null),[manageError,setManageError]=useState('');
  const rows=useMemo(()=>{
    if(tab===0)return products.filter(product=>{
      const productDate=(product.updatedAt||product.createdAt||'').slice(0,10);
      return (!filters.group||product.warehouseGroup===filters.group)&&includesSearch(product,filters.search)&&inDateRange(productDate,filters.from,filters.to);
    });
    const allowedTypes=movementTypes[tab];
    return movements.filter(movement=>{
      const warehouseMatch=!filters.group||movement.warehouseGroup===filters.group||movement.sourceWarehouse===filters.group||movement.destinationWarehouse===filters.group;
      const typeMatch=!allowedTypes||allowedTypes.includes(movement.transactionType);
      return warehouseMatch&&typeMatch&&includesSearch(movement,filters.search)&&inDateRange(movement.transactionDate,filters.from,filters.to);
    }).sort((a,b)=>`${b.transactionDate} ${b.transactionTime}`.localeCompare(`${a.transactionDate} ${a.transactionTime}`));
  },[tab,products,movements,filters]);
  const change=(key,value)=>setDraft(current=>({...current,[key]:value}));
  const search=()=>{if(draft.from&&draft.to&&draft.from>draft.to){setError('วันที่เริ่มต้นต้องไม่เกินวันที่สิ้นสุด');return}setFilters({...draft});setError('')};
  const clear=()=>{setDraft(emptyFilters);setFilters(emptyFilters);setError('')};
  const filterSummary=[filters.from&&`ตั้งแต่ ${filters.from}`,filters.to&&`ถึง ${filters.to}`,filters.group&&`คลัง ${filters.group}`,filters.search&&`คำค้น “${filters.search}”`].filter(Boolean).join(' · ');
  const exportPdf=()=>printHtml(reportHtml(reports[tab],rows,tab,filterSummary),`${reports[tab]} - CSP`);
  const reprint=documentNo=>{const saved=documents.find(document=>document.documentNo===documentNo);const related=movements.filter(movement=>movement.documentNo===documentNo);const data=saved||movementDocument(related,tab);printHtml(documentHtml(data),data.title)};
  const openManage=(mode,movement)=>{setManage({mode,movement});setQuantity(movement.quantityIn||movement.quantityOut);setReason('');setEvidence(null);setManageError('')};
  const loadEvidence=event=>{const file=event.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/')){setManageError('กรุณาเลือกไฟล์รูปภาพเท่านั้น');return}if(file.size>5*1024*1024){setManageError('รูปภาพต้องมีขนาดไม่เกิน 5 MB');return}const reader=new FileReader();reader.onload=()=>{setEvidence({name:file.name,type:file.type,size:file.size,dataUrl:reader.result});setManageError('')};reader.readAsDataURL(file)};
  const confirmManage=()=>{try{requestMovementChange(manage.mode==='edit'?'EDIT':'DELETE',manage.movement.id,quantity,reason,evidence);setManage(null)}catch(actionError){setManageError(actionError.message)}};

  return <>
    <PageHeader title="รายงาน" subtitle="วิเคราะห์ข้อมูลคลังสินค้าและส่งออก Excel/PDF" actions={<><button className="btn secondary" onClick={exportPdf}><FileText/> Export PDF</button><ExportButton rows={rows} name={`CSP-report-${tab+1}`}/></>}/>
    <div className="report-tabs">{reports.map((report,index)=><button key={report} className={tab===index?'active':''} onClick={()=>setTab(index)}>{report}</button>)}</div>
    <div className="card filters">
      <label>วันที่เริ่มต้น<input type="date" value={draft.from} onChange={event=>change('from',event.target.value)}/></label>
      <label>วันที่สิ้นสุด<input type="date" value={draft.to} onChange={event=>change('to',event.target.value)}/></label>
      <label>กลุ่มคลัง<select value={draft.group} onChange={event=>change('group',event.target.value)}><option value="">ทุกคลัง</option>{warehouseGroups.map(group=><option value={group.id} key={group.id}>{group.name}</option>)}</select></label>
      <label>ค้นหา<input value={draft.search} onChange={event=>change('search',event.target.value)} onKeyDown={event=>event.key==='Enter'&&search()} placeholder="Barcode / รหัส / ชื่อ / เลขเอกสาร"/></label>
      <button className="btn primary" onClick={search}>ค้นหา</button><button className="btn ghost" onClick={clear}>ล้างค่า</button>
      {error&&<div className="alert full">{error}</div>}
    </div>
    <div className="card"><div className="card-title"><div><h2>{reports[tab]}</h2><p>พบข้อมูล {rows.length} รายการ{filterSummary&&` · ${filterSummary}`}</p></div><BarChart3/></div><div className="table-wrap"><table>
      <thead>{tab===0?<tr><th>รหัสสินค้า</th><th>ชื่อสินค้า</th><th>คลัง</th><th>หน่วย</th><th>คงเหลือ</th><th>สถานะ</th><th>วันที่แก้ไขล่าสุด</th></tr>:<tr><th>วันที่</th><th>เลขที่เอกสาร</th><th>สินค้า</th><th>คลัง</th><th>ประเภท</th><th>รับ</th><th>จ่าย</th>{[1,2,3].includes(tab)&&<th>เอกสาร</th>}</tr>}</thead>
      <tbody>{tab===0?rows.map(product=><tr key={product.id}><td>{product.productCode}<small>{product.barcode}</small></td><td>{product.productName}</td><td>{product.warehouseGroup}</td><td>{product.unit}</td><td>{product.currentStock}</td><td><StatusBadge status={stockStatus(product)}/></td><td>{(product.updatedAt||product.createdAt||'').slice(0,10)||'—'}</td></tr>):rows.map(movement=><tr key={movement.id}><td>{movement.transactionDate}<small>{movement.transactionTime}</small></td><td>{movement.documentNo}</td><td>{movement.productName}<small>{movement.productCode}</small></td><td>{movement.warehouseGroup}</td><td>{movementLabels[movement.transactionType]}</td><td>{movement.quantityIn||'—'}</td><td>{movement.quantityOut||'—'}</td>{[1,2,3].includes(tab)&&<td><div className="row-actions transaction-actions"><button onClick={()=>reprint(movement.documentNo)} title="พิมพ์ซ้ำ"><Printer/></button><button onClick={()=>openManage('edit',movement)} title="แก้ไขจำนวน"><Pencil/></button><button className="danger" onClick={()=>openManage('delete',movement)} title="ลบรายการ"><Trash2/></button></div></td>}</tr>)}</tbody>
    </table>{!rows.length&&<Empty/>}</div></div>
    {manage&&<Modal title={manage.mode==='edit'?'แก้ไขจำนวนสินค้า':'ขอลบรายการสินค้า'} onClose={()=>setManage(null)}><div className="change-request-form"><div className="request-summary"><Clock3/><div><b>ส่งคำขอเพื่อรออนุมัติ</b><span>รายการจะยังไม่กระทบ Stock จนกว่าระดับจัดการจะอนุมัติ</span></div></div><div className="request-detail"><div><span>เลขที่เอกสาร</span><b>{manage.movement.documentNo}</b></div><div><span>รหัสสินค้า</span><b>{manage.movement.productCode}</b></div><div className="full"><span>สินค้า</span><b>{manage.movement.productName}</b></div></div>{manage.mode==='edit'&&<label>จำนวนใหม่<input type="number" min="1" value={quantity} onChange={event=>setQuantity(event.target.value)}/></label>}<label>เหตุผล{manage.mode==='delete'?'การลบ':'การแก้ไข'}<textarea value={reason} onChange={event=>setReason(event.target.value)} placeholder="กรุณาระบุเหตุผลอย่างชัดเจน"/></label><label className="evidence-upload"><span>ภาพหลักฐาน <b>*</b></span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={loadEvidence}/><span className="upload-hint"><ImagePlus/> {evidence?evidence.name:'รองรับ JPG, PNG, WebP ขนาดไม่เกิน 5 MB'}</span></label>{evidence&&<img className="evidence-preview" src={evidence.dataUrl} alt="ภาพหลักฐานที่เลือก"/>}{manageError&&<div className="alert">{manageError}</div>}</div><div className="modal-actions"><button className="btn ghost" onClick={()=>setManage(null)}>ยกเลิก</button><button className={manage.mode==='delete'?'btn danger-btn':'btn primary'} disabled={!reason.trim()||!evidence||(manage.mode==='edit'&&+quantity<=0)} onClick={confirmManage}>{manage.mode==='edit'?'แก้ไข':'ส่งคำขอลบ'}</button></div></Modal>}
  </>;
}

const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function reportHtml(title,rows,tab,filter){const header=tab===0?'<th>รหัสสินค้า</th><th>ชื่อสินค้า</th><th>คลัง</th><th>หน่วย</th><th>คงเหลือ</th>':'<th>วันที่</th><th>เลขที่เอกสาร</th><th>สินค้า</th><th>คลัง</th><th>ประเภท</th><th>รับ</th><th>จ่าย</th>';const body=tab===0?rows.map(row=>`<tr><td>${escape(row.productCode)}</td><td>${escape(row.productName)}</td><td>${escape(row.warehouseGroup)}</td><td>${escape(row.unit)}</td><td class="num">${fmt(row.currentStock)}</td></tr>`).join(''):rows.map(row=>`<tr><td>${escape(row.transactionDate)}</td><td>${escape(row.documentNo)}</td><td>${escape(row.productName)}</td><td>${escape(row.warehouseGroup)}</td><td>${escape(movementLabels[row.transactionType])}</td><td class="num">${row.quantityIn||'—'}</td><td class="num">${row.quantityOut||'—'}</td></tr>`).join('');return `<div class="print-document"><div class="report-title"><h1>CSP Foods Supply Co., Ltd.</h1><h2>${escape(title)}</h2></div><div class="report-filter">${escape(filter||'ทุกข้อมูล')} · พิมพ์เมื่อ ${new Date().toLocaleString('th-TH')}</div><table class="print-table"><thead><tr>${header}</tr></thead><tbody>${body}</tbody></table></div>`}
function movementDocument(rows,tab){const first=rows[0]||{};const type=tab===1?'receive':tab===2?'issue':'transfer',documentRows=type==='transfer'&&rows.some(row=>row.transactionType==='TRANSFER_OUT')?rows.filter(row=>row.transactionType==='TRANSFER_OUT'):rows;return{type,title:type==='receive'?'ใบรับสินค้าเข้าคลัง':type==='issue'?'ใบจ่ายสินค้าออกจากคลัง':'ใบโอนสินค้าระหว่างคลัง',documentNo:first.documentNo||'—',date:first.transactionDate||'—',group:first.sourceWarehouse||first.warehouseGroup||'—',destination:first.destinationWarehouse||'—',partner:'—',reference:'—',remark:first.remark||'',userName:first.userName||'—',items:documentRows.map(row=>({id:row.id,productCode:row.productCode,barcode:row.barcode,productName:row.productName,unit:row.unit,qty:row.quantityIn||row.quantityOut,price:0})),signatures:type==='receive'?['ผู้ส่งมอบ','ผู้รับสินค้า','ผู้ตรวจสอบ']:type==='issue'?['ผู้จ่ายสินค้า','ผู้รับสินค้า','ผู้อนุมัติ']:['ผู้โอนสินค้า','ผู้รับโอน','ผู้อนุมัติ']}}
function documentHtml(data){const rows=data.items.map((item,index)=>`<tr><td>${index+1}</td><td>${escape(item.productCode)}<small>${escape(item.barcode)}</small></td><td>${escape(item.productName)}</td><td>${escape(item.unit)}</td><td class="num">${fmt(item.qty)}</td></tr>`).join('');return `<div class="print-document"><div class="print-company"><div><h1>CSP Foods Supply Co., Ltd.</h1><p>บริษัท ซีเอสพี ฟู้ดส์ ซัพพลาย จำกัด</p></div><div><h2>${escape(data.title)}</h2><b>เลขที่ ${escape(data.documentNo)}</b></div></div><div class="print-meta"><div><span>วันที่เอกสาร</span><b>${escape(data.date)}</b></div><div><span>คลังต้นทาง</span><b>${escape(data.group)}</b></div>${data.type==='transfer'?`<div><span>คลังปลายทาง</span><b>${escape(data.destination)}</b></div>`:''}<div><span>ผู้ทำรายการ</span><b>${escape(data.userName)}</b></div><div><span>เลขที่อ้างอิง</span><b>${escape(data.reference||'—')}</b></div></div><table class="print-table"><thead><tr><th>ลำดับ</th><th>รหัสสินค้า</th><th>รายละเอียดสินค้า</th><th>หน่วย</th><th>จำนวน</th></tr></thead><tbody>${rows}</tbody></table><div class="print-remark"><b>หมายเหตุ:</b> ${escape(data.remark||'—')}</div><div class="signature-grid">${data.signatures.map(label=>`<div><div class="signature-line"></div><b>${escape(label)}</b><span>(........................................................)</span><span>วันที่ ........../........../..........</span></div>`).join('')}</div></div>`}
