import {useState} from 'react';
import {Warehouse,Scale,Tags,TableProperties,Hash,DatabaseBackup,RotateCcw,Save,Users,Download,Upload,Trash2} from 'lucide-react';
import {useApp} from '../context/AppContext';
import {warehouseGroups,units} from '../data/constants';
import {PageHeader,ConfirmModal} from '../components/common';
import {createPasswordHash,getAuthSession,getUsers,saveUsers} from '../utils/auth';

const tabs=[['กลุ่มคลัง',Warehouse],['หน่วยสินค้า',Scale],['ประเภทการจ่าย',Tags],['หน้าตาตาราง',TableProperties],['เลขที่เอกสาร',Hash],['ผู้ใช้งาน',Users],['สำรองข้อมูล',DatabaseBackup]];
const backupKeys=['csp_products','csp_movements','csp_lots','csp_documents','csp_audit_logs','csp_stock_counts','csp_storage_locations','csp_warehouse_periods','csp_viewing_period','csp_opening_closures','csp_users','csp_transaction_drafts'];

export default function SettingsPage(){
  const [tab,setTab]=useState(0),[confirm,setConfirm]=useState(false),[usersList,setUsersList]=useState(getUsers),[userForm,setUserForm]=useState({username:'',password:'',name:'',role:'USER'}),[error,setError]=useState('');
  const {reset,setToast}=useApp();
  const addUser=()=>{const username=userForm.username.trim(),name=userForm.name.trim();if(!username||!name||userForm.password.length<4){setError('กรุณากรอกชื่อ ชื่อผู้ใช้ และรหัสผ่านอย่างน้อย 4 ตัวอักษร');return}if(usersList.some(item=>item.username.toLowerCase()===username.toLowerCase())){setError('ชื่อผู้ใช้งานนี้มีอยู่แล้ว');return}const next=[...usersList,{id:`USR-${Date.now()}`,username,name,passwordHash:createPasswordHash(userForm.password),role:userForm.role,roleLabel:userForm.role==='APPROVER'?'Admin':'User',active:true}];saveUsers(next);setUsersList(next);setUserForm({username:'',password:'',name:'',role:'USER'});setError('');setToast('เพิ่มผู้ใช้งานแล้ว')};
  const removeUser=id=>{if(getAuthSession()?.userId===id){setError('ไม่สามารถลบบัญชีที่กำลังเข้าสู่ระบบได้');return}const next=usersList.filter(item=>item.id!==id);saveUsers(next);setUsersList(next);setToast('ลบผู้ใช้งานแล้ว')};
  const exportBackup=()=>{const data=Object.fromEntries(backupKeys.filter(key=>localStorage.getItem(key)!==null).map(key=>[key,JSON.parse(localStorage.getItem(key))]));const payload={app:'CSP Warehouse',version:1,exportedAt:new Date().toISOString(),data},url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=`csp-warehouse-backup-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);setToast('ดาวน์โหลดไฟล์สำรอง JSON แล้ว')};
  const importBackup=async event=>{try{const file=event.target.files?.[0];if(!file)return;const payload=JSON.parse(await file.text());if(payload.app!=='CSP Warehouse'||!payload.data||typeof payload.data!=='object')throw new Error('รูปแบบไฟล์สำรองไม่ถูกต้อง');backupKeys.forEach(key=>{if(Object.hasOwn(payload.data,key))localStorage.setItem(key,JSON.stringify(payload.data[key]))});setToast('กู้คืนข้อมูลแล้ว ระบบกำลังโหลดใหม่');setTimeout(()=>window.location.reload(),500)}catch(importError){setError(importError.message||'ไม่สามารถอ่านไฟล์สำรองได้')}finally{event.target.value=''}};
  return <><PageHeader title="ตั้งค่าระบบ" subtitle="กำหนดค่าพื้นฐานและจัดการข้อมูลระบบ"/><div className="settings-layout"><div className="settings-tabs">{tabs.map(([name,Icon],index)=><button className={tab===index?'active':''} key={name} onClick={()=>{setTab(index);setError('')}}><Icon/>{name}</button>)}</div><div className="card settings-content"><h2>{tabs[tab][0]}</h2><p>จัดการค่าที่ใช้ร่วมกันภายในระบบ</p>{error&&<div className="alert">{error}</div>}
    {tab===0&&<div className="setting-list">{warehouseGroups.map((group,index)=><div key={group.id}><span className="order">{index+1}</span><div><b>{group.name}</b><small>รหัส: {group.id}</small></div><span className="badge green">ใช้งาน</span></div>)}</div>}
    {tab===1&&<div className="setting-list">{units.map((unit,index)=><div key={unit}><span className="order">{index+1}</span><b>{unit}</b><span className="badge green">ใช้งาน</span></div>)}</div>}
    {tab===2&&<div className="setting-list">{['ส่งให้สาขา','เบิกใช้งาน','คืน Supplier','สินค้าเสียหาย','ปรับปรุง Stock'].map((name,index)=><div key={name}><span className="order">{index+1}</span><b>{name}</b><span className="badge green">ใช้งาน</span></div>)}</div>}
    {tab===3&&<div className="form-grid"><label>จำนวนรายการต่อหน้า<select><option>10</option><option>20</option><option>50</option></select></label><label>ความหนาแน่นตาราง<select><option>ปกติ</option><option>กระชับ</option></select></label></div>}
    {tab===4&&<div className="form-grid"><label>รับสินค้า<input value="RCV" readOnly/></label><label>จ่ายสินค้า<input value="ISS" readOnly/></label><label>โอนสินค้า<input value="TRF" readOnly/></label><label>รูปแบบวันที่<input value="YYYYMMDD" readOnly/></label></div>}
    {tab===5&&<><div className="form-grid"><label>ชื่อพนักงาน<input value={userForm.name} onChange={event=>setUserForm({...userForm,name:event.target.value})}/></label><label>ชื่อผู้ใช้งาน<input value={userForm.username} onChange={event=>setUserForm({...userForm,username:event.target.value})}/></label><label>รหัสผ่านใหม่<input type="password" value={userForm.password} onChange={event=>setUserForm({...userForm,password:event.target.value})}/></label><label>สิทธิ์<select value={userForm.role} onChange={event=>setUserForm({...userForm,role:event.target.value})}><option value="USER">ผู้ใช้งาน</option><option value="APPROVER">ผู้ดูแลระบบ/ผู้อนุมัติ</option></select></label></div><button className="btn primary" onClick={addUser}><Save/> เพิ่มผู้ใช้งาน</button><div className="setting-list">{usersList.map(item=><div key={item.id}><div><b>{item.name}</b><small>{item.username} · {item.roleLabel}</small></div><span className="badge green">ใช้งาน</span><button className="icon-btn danger" onClick={()=>removeUser(item.id)} aria-label={`ลบ ${item.username}`}><Trash2/></button></div>)}</div></>}
    {tab===6&&<div className="backup-box"><DatabaseBackup/><h3>สำรองข้อมูลทั้งหมดเป็น JSON</h3><p>ครอบคลุมสินค้า Stock Card, Lot, เอกสาร, ผู้ใช้, รอบคลัง, Audit Log และแบบร่าง</p><div className="actions backup-actions"><button className="btn primary" onClick={exportBackup}><Download/> ดาวน์โหลด Backup</button><label className="btn secondary"><Upload/> กู้คืนจาก JSON<input type="file" accept="application/json,.json" hidden onChange={importBackup}/></label><button className="btn danger-btn" onClick={()=>setConfirm(true)}><RotateCcw/> คืนค่า Mock Data</button></div></div>}
    {tab<5&&<button className="btn primary settings-save" onClick={()=>setToast('บันทึกการตั้งค่าแล้ว')}><Save/> บันทึกการตั้งค่า</button>}
  </div></div>{confirm&&<ConfirmModal title="คืนค่าข้อมูลตัวอย่าง" text="ข้อมูลที่แก้ไขทั้งหมดจะถูกแทนที่ด้วย Mock Data เริ่มต้น ต้องการดำเนินการหรือไม่" onClose={()=>setConfirm(false)} onConfirm={()=>{reset();setConfirm(false)}}/>}</>;
}
