import {useMemo,useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {ScrollText,ArrowDownToLine,ArrowUpFromLine,ArrowRightLeft,PackageCheck,Search} from 'lucide-react';
import {useApp} from '../context/AppContext';
import {warehouseGroups,movementLabels} from '../data/constants';
import {fmt,stockStatus} from '../utils/helpers';
import {PageHeader,StatCard,ExportButton,StatusBadge,Empty} from '../components/common';

export default function StockCardPage(){
  const {products,movements}=useApp(),[params]=useSearchParams();
  const [product,setProduct]=useState(params.get('product')||''),[productSearch,setProductSearch]=useState(''),[group,setGroup]=useState(''),[type,setType]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[order,setOrder]=useState('desc');
  const filteredProducts=useMemo(()=>products.filter(item=>!productSearch||`${item.barcode} ${item.productCode} ${item.productName}`.toLowerCase().includes(productSearch.toLowerCase())),[products,productSearch]);
  const selected=products.find(item=>item.id===product);
  const list=useMemo(()=>movements.filter(movement=>(!product||movement.productId===product)&&(!productSearch||`${movement.barcode} ${movement.productCode} ${movement.productName}`.toLowerCase().includes(productSearch.toLowerCase()))&&(!group||movement.warehouseGroup===group)&&(!type||movement.transactionType===type)&&(!from||movement.transactionDate>=from)&&(!to||movement.transactionDate<=to)).sort((a,b)=>order==='desc'?b.createdAt.localeCompare(a.createdAt):a.createdAt.localeCompare(b.createdAt)),[movements,product,productSearch,group,type,from,to,order]);
  const totals={in:list.reduce((sum,movement)=>sum+movement.quantityIn,0),out:list.reduce((sum,movement)=>sum+movement.quantityOut,0),tin:list.filter(movement=>movement.transactionType==='TRANSFER_IN').reduce((sum,movement)=>sum+movement.quantityIn,0),tout:list.filter(movement=>movement.transactionType==='TRANSFER_OUT').reduce((sum,movement)=>sum+movement.quantityOut,0)};
  const clear=()=>{setProduct('');setProductSearch('');setGroup('');setType('');setFrom('');setTo('')};
  return <>
    <PageHeader title="Stock Card" subtitle="ตรวจสอบประวัติและยอดคงเหลือต่อเนื่องของสินค้า" actions={<ExportButton rows={list.map(movement=>({...movement,transactionType:movementLabels[movement.transactionType]}))} name="CSP-stock-card"/>}/>
    <div className="card filters"><label>ค้นหาสินค้า<div className="filter-search"><Search/><input value={productSearch} onChange={event=>{setProductSearch(event.target.value);setProduct('')}} placeholder="Barcode / รหัส / ชื่อสินค้า"/></div></label><label>สินค้า<select value={product} onChange={event=>setProduct(event.target.value)}><option value="">ทุกสินค้า ({filteredProducts.length})</option>{filteredProducts.map(item=><option value={item.id} key={item.id}>{item.productCode} · {item.productName}</option>)}</select></label><label>กลุ่มคลัง<select value={group} onChange={event=>setGroup(event.target.value)}><option value="">ทุกคลัง</option>{warehouseGroups.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>ประเภท<select value={type} onChange={event=>setType(event.target.value)}><option value="">ทุกประเภท</option>{Object.entries(movementLabels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label>วันที่เริ่มต้น<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>วันที่สิ้นสุด<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label><button className="btn ghost" onClick={clear}>ล้างค่า</button></div>
    {selected&&<div className="product-banner"><div><small>{selected.barcode} · {selected.productCode}</small><h2>{selected.productName}</h2><span>{selected.warehouseGroup} · {selected.unit}</span></div><div><small>Stock ปัจจุบัน</small><b>{fmt(selected.currentStock)}</b><StatusBadge status={stockStatus(selected)}/></div></div>}
    <div className="stats-grid compact"><StatCard icon={PackageCheck} label="Stock ปัจจุบัน" value={fmt(selected?.currentStock??products.reduce((sum,item)=>sum+item.currentStock,0))} unit="หน่วย"/><StatCard icon={ArrowDownToLine} label="รับเข้ารวม" value={fmt(totals.in)} unit="หน่วย" color="green"/><StatCard icon={ArrowUpFromLine} label="จ่ายออกรวม" value={fmt(totals.out)} unit="หน่วย" color="orange"/><StatCard icon={ArrowRightLeft} label="โอนเข้า / ออก" value={`${fmt(totals.tin)} / ${fmt(totals.tout)}`} unit="หน่วย" color="purple"/></div>
    <div className="card"><div className="card-title"><h2>ตารางความเคลื่อนไหว</h2><select value={order} onChange={event=>setOrder(event.target.value)}><option value="desc">ใหม่ไปเก่า</option><option value="asc">เก่าไปใหม่</option></select></div><div className="table-wrap"><table><thead><tr><th>#</th><th>วันที่ / เวลา</th><th>เอกสาร</th><th>ประเภท</th><th>ต้นทาง → ปลายทาง</th><th>รับเข้า</th><th>จ่ายออก</th><th>คงเหลือ</th><th>ผู้ทำรายการ</th></tr></thead><tbody>{list.map((movement,index)=><tr key={movement.id}><td>{index+1}</td><td>{movement.transactionDate}<small>{movement.transactionTime}</small></td><td><b>{movement.documentNo}</b><small>{movement.productName}</small></td><td><span className={`movement-badge ${movement.transactionType.toLowerCase()}`}>{movementLabels[movement.transactionType]}</span></td><td>{movement.sourceWarehouse||'—'} → {movement.destinationWarehouse||'—'}</td><td className="qty-in">{movement.quantityIn?`+${fmt(movement.quantityIn)}`:'—'}</td><td className="qty-out">{movement.quantityOut?`-${fmt(movement.quantityOut)}`:'—'}</td><td><b>{fmt(movement.balanceAfter)}</b></td><td>{movement.userName}</td></tr>)}</tbody></table>{!list.length&&<Empty/>}</div></div>
  </>;
}
