import {useMemo,useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {ArrowDownToLine,ArrowUpFromLine,ArrowRightLeft,PackageCheck,Search} from 'lucide-react';
import {useApp} from '../context/AppContext';
import {warehouseGroups,movementLabels} from '../data/constants';
import {fmt,stockStatus} from '../utils/helpers';
import {PageHeader,StatCard,ExportButton,StatusBadge,Empty} from '../components/common';

const normalizeLotDate=value=>{const text=String(value||'').trim();if(/^\d{4}-\d{2}-\d{2}$/.test(text))return text;const match=text.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{4})$/);return match?`${match[3]}-${match[2].padStart(2,'0')}-${match[1].padStart(2,'0')}`:''};

export default function StockCardPage(){
  const {products,movements,lots}=useApp(),[params]=useSearchParams();
  const [product,setProduct]=useState(params.get('product')||''),[productSearch,setProductSearch]=useState(params.get('location')||''),[lotSearch,setLotSearch]=useState(''),[group,setGroup]=useState(params.get('group')||''),[type,setType]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
  const filteredProducts=useMemo(()=>products.filter(item=>!productSearch||`${item.productName} ${item.productCode} ${item.barcode}`.toLowerCase().includes(productSearch.toLowerCase())),[products,productSearch]);
  const selected=products.find(item=>item.id===product);
  const list=useMemo(()=>movements.filter(movement=>(!product||movement.productId===product)&&(!productSearch||`${movement.productName} ${movement.productCode} ${movement.barcode} ${movement.locationName}`.toLowerCase().includes(productSearch.toLowerCase()))&&(!lotSearch||normalizeLotDate(movement.lotNo)===lotSearch)&&(!group||movement.warehouseGroup===group)&&(!type||movement.transactionType===type)&&(!from||movement.transactionDate>=from)&&(!to||movement.transactionDate<=to)),[movements,product,productSearch,lotSearch,group,type,from,to]);
  const lotList=useMemo(()=>lots.filter(lot=>(!product||lot.productId===product)&&(!productSearch||`${lot.productName} ${lot.productCode} ${lot.barcode} ${lot.locationName}`.toLowerCase().includes(productSearch.toLowerCase()))&&(!lotSearch||normalizeLotDate(lot.lotNo)===lotSearch)&&(!group||lot.warehouseGroup===group)).sort((a,b)=>a.receivedDate.localeCompare(b.receivedDate)),[lots,product,productSearch,lotSearch,group]);
  const totals={in:list.reduce((sum,movement)=>sum+movement.quantityIn,0),out:list.reduce((sum,movement)=>sum+movement.quantityOut,0),tin:list.filter(movement=>movement.transactionType==='TRANSFER_IN').reduce((sum,movement)=>sum+movement.quantityIn,0),tout:list.filter(movement=>movement.transactionType==='TRANSFER_OUT').reduce((sum,movement)=>sum+movement.quantityOut,0)};
  const clear=()=>{setProduct('');setProductSearch('');setLotSearch('');setGroup('');setType('');setFrom('');setTo('')};
  return <>
    <PageHeader title="Stock Card" subtitle="ตรวจสอบวันที่รับ วันที่จ่าย และยอดคงเหลือแยกตาม Lot" actions={<ExportButton rows={list.map(movement=>({...movement,transactionType:movementLabels[movement.transactionType]}))} name="CSP-stock-card"/>}/>
    <div className="card filters"><label>ค้นหาสินค้า / จุดเก็บ<div className="filter-search"><Search/><input value={productSearch} onChange={event=>{setProductSearch(event.target.value);setProduct('')}} placeholder="รหัสสินค้า ชื่อสินค้า หรือจุดเก็บ"/></div></label><label>ค้นหา Lot (วันที่)<input type="date" value={lotSearch} onChange={event=>setLotSearch(event.target.value)}/></label><label>สินค้า<select value={product} onChange={event=>setProduct(event.target.value)}><option value="">ทุกสินค้า ({filteredProducts.length})</option>{filteredProducts.map(item=><option value={item.id} key={item.id}>{item.productCode} · {item.productName} · {item.warehouseGroup}</option>)}</select></label><label>กลุ่มคลัง<select value={group} onChange={event=>setGroup(event.target.value)}><option value="">ทุกคลัง</option>{warehouseGroups.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>ประเภท<select value={type} onChange={event=>setType(event.target.value)}><option value="">ทุกประเภท</option>{Object.entries(movementLabels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label>วันที่เริ่มต้น<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>วันที่สิ้นสุด<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label><button className="btn ghost" onClick={clear}>ล้างค่า</button></div>
    {selected&&<div className="product-banner"><div><small>{selected.barcode} · {selected.productCode}</small><h2>{selected.productName}</h2><span>{selected.warehouseGroup} · {selected.unit}</span></div><div><small>Stock ปัจจุบัน</small><b>{fmt(selected.currentStock)}</b><StatusBadge status={stockStatus(selected)}/></div></div>}
    <div className="stats-grid compact"><StatCard icon={PackageCheck} label="Stock ปัจจุบัน" value={fmt(selected?.currentStock??products.reduce((sum,item)=>sum+item.currentStock,0))} unit={selected?.unit||'หลายหน่วย'}/><StatCard icon={ArrowDownToLine} label="รับเข้ารวม" value={fmt(totals.in)} unit={selected?.unit||'หลายหน่วย'} color="green"/><StatCard icon={ArrowUpFromLine} label="จ่ายออกรวม" value={fmt(totals.out)} unit={selected?.unit||'หลายหน่วย'} color="orange"/><StatCard icon={ArrowRightLeft} label="โอนเข้า / ออก" value={`${fmt(totals.tin)} / ${fmt(totals.tout)}`} unit={selected?.unit||'หลายหน่วย'} color="purple"/></div>
    <div className="card"><div className="card-title"><h2>Lot คงเหลือ</h2><ExportButton rows={lotList} name="CSP-lot-balance"/></div><div className="table-wrap"><table><thead><tr><th>รหัสสินค้า</th><th>ชื่อสินค้า</th><th>จุดเก็บ</th><th>คลัง</th><th>Lot</th><th>วันที่รับ</th><th>หน่วย</th><th>รับทั้งหมด</th><th>คงเหลือ Lot</th></tr></thead><tbody>{lotList.map(lot=><tr key={lot.id}><td><b>{lot.productCode}</b><small>{lot.barcode}</small></td><td>{lot.productName}</td><td>{lot.locationName||'ไม่ระบุจุดเก็บ'}</td><td>{lot.warehouseGroup}</td><td><b>{lot.lotNo}</b></td><td>{lot.receivedDate}</td><td>{products.find(item=>item.id===lot.productId)?.unit||'—'}</td><td>{fmt(lot.quantityReceived)}</td><td><b>{fmt(lot.quantityRemaining)}</b></td></tr>)}</tbody></table>{!lotList.length&&<Empty/>}</div></div>
  </>;
}
