import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ClipboardCheck,Eye,FileClock,FilePlus2,FolderOpen,Minus,Plus,Search,Trash2,TriangleAlert} from 'lucide-react';
import {useApp} from '../context/AppContext';
import {warehouseGroups} from '../data/constants';
import {PageHeader,Empty,ConfirmModal} from '../components/common';
import {fmt} from '../utils/helpers';

const normalizeDate=value=>{const text=String(value||'');if(/^\d{4}-\d{2}-\d{2}$/.test(text))return text;const match=text.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{4})$/);return match?`${match[3]}-${match[2].padStart(2,'0')}-${match[1].padStart(2,'0')}`:''};

export default function StockCountPage(){
  const {products,lots,stockCounts,assertOpenPeriod,createStockCount,finishStockCount,deleteStockCount,adjustStock,setToast}=useApp();
  const [mode,setMode]=useState('home'),[sessionId,setSessionId]=useState(''),[docWarehouse,setDocWarehouse]=useState(''),[docDate,setDocDate]=useState(new Date().toISOString().slice(0,10));
  const [search,setSearch]=useState(''),[productId,setProductId]=useState(''),[lotDate,setLotDate]=useState(''),[counted,setCounted]=useState(0),[confirm,setConfirm]=useState(false),[historyId,setHistoryId]=useState(''),[deleteId,setDeleteId]=useState('');
  const session=stockCounts.find(item=>item.id===sessionId),history=stockCounts.find(item=>item.id===historyId);
  const matches=useMemo(()=>products.filter(product=>product.warehouseGroup===session?.warehouseGroup&&(product.id===productId||!search||`${product.productCode} ${product.productName}`.toLowerCase().includes(search.toLowerCase()))).slice(0,30),[products,session?.warehouseGroup,search,productId]);
  const product=products.find(item=>item.id===productId),matchedLots=lots.filter(lot=>lot.productId===productId&&normalizeDate(lot.lotNo)===lotDate),systemQuantity=matchedLots.reduce((sum,lot)=>sum+(+lot.quantityRemaining||0),0),lotExists=matchedLots.length>0,difference=counted-systemQuantity;
  const start=()=>{try{assertOpenPeriod(docDate);const created=createStockCount({warehouseGroup:docWarehouse,date:docDate});window.history.pushState({stockCount:true},'');setSessionId(created.id);setMode('count')}catch(error){setToast(error.message)}};
  const chooseProduct=item=>{setProductId(item.id);setLotDate('');setCounted(0);setSearch(`${item.productCode} · ${item.productName}`)};
  const chooseDate=value=>{setLotDate(value);const existing=lots.filter(lot=>lot.productId===productId&&normalizeDate(lot.lotNo)===value);setCounted(existing.reduce((sum,lot)=>sum+(+lot.quantityRemaining||0),0))};
  const submit=()=>{try{assertOpenPeriod(session?.countDate);adjustStock(sessionId,productId,lotDate,counted);setConfirm(false)}catch(error){setToast(error.message)}};
  const closeSession=()=>{finishStockCount(sessionId);setSessionId('');setMode('home');setProductId('');setLotDate('')};
  const openSession=item=>{window.history.pushState({stockCount:true},'');setSessionId(item.id);setProductId('');setLotDate('');setSearch('');setHistoryId('');setMode('count')};
  const confirmDelete=()=>{try{deleteStockCount(deleteId);if(deleteId===sessionId)setSessionId('');if(deleteId===historyId)setHistoryId('');setDeleteId('')}catch(error){setToast(error.message)}};
  const openCount=stockCounts.filter(item=>item.status==='OPEN');
  useEffect(()=>{const goBack=()=>{setProductId('');setLotDate('');setSearch('');setHistoryId('');setMode('home')};window.addEventListener('popstate',goBack);window.addEventListener('csp-stock-count-back',goBack);return()=>{window.removeEventListener('popstate',goBack);window.removeEventListener('csp-stock-count-back',goBack)}},[]);
  if(mode==='home')return <><PageHeader title="นับสต็อกสินค้า" subtitle="สร้างเอกสารตรวจนับหลายใบและสลับเข้าไปนับได้" actions={<button className="btn secondary" onClick={()=>setMode('history')}><FileClock/> รายการเอกสาร ({stockCounts.length})</button>}/>{openCount.length>0&&<div className="card count-open-documents"><div className="card-title"><div><h2>เอกสารที่กำลังนับ</h2><p>เลือกเอกสารเพื่อกลับเข้าไปนับต่อ</p></div><span className="movement-result-count">{openCount.length} เอกสาร</span></div><div className="count-document-switcher">{openCount.map(item=><button key={item.id} onClick={()=>openSession(item)}><FolderOpen/><span><b>{item.documentNo}</b><small>{item.name} · {item.countDate} · นับแล้ว {item.lines.length} ครั้ง</small></span></button>)}</div></div>}<div className="count-document-start card"><div className="count-document-icon"><FilePlus2/></div><h2>สร้างเอกสารนับสต็อก</h2><p>เลือกคลังและวันที่ตรวจนับ สามารถสร้างหลายเอกสารและกลับมาสลับนับภายหลังได้</p><div className="form-grid"><label>คลังสินค้า<select value={docWarehouse} onChange={event=>setDocWarehouse(event.target.value)}><option value="">— เลือกคลังสินค้า —</option>{warehouseGroups.map(group=><option key={group.id} value={group.id}>{group.name}</option>)}</select></label><label>วันที่ตรวจนับ<input type="date" value={docDate} onChange={event=>setDocDate(event.target.value)}/></label></div><button className="btn primary" onClick={start}><ClipboardCheck/> สร้างเอกสารและเริ่มนับ</button></div></>;
  if(mode==='history')return <><PageHeader title="รายการเอกสารนับ Stock" subtitle="สลับเอกสารที่กำลังนับ ตรวจสอบประวัติ หรือลบเอกสาร" actions={<><button className="btn primary" onClick={()=>{setHistoryId('');setMode('home')}}><FilePlus2/> สร้างเอกสารใหม่</button><button className="btn ghost" onClick={()=>{setHistoryId('');setMode(sessionId?'count':'home')}}><ArrowLeft/> กลับ</button></>}/>{history?<HistoryDetail document={history} onBack={()=>setHistoryId('')} onCount={history.status==='OPEN'?()=>openSession(history):null} onDelete={()=>setDeleteId(history.id)}/>:<div className="card"><div className="table-wrap"><table><thead><tr><th>เลขที่เอกสาร</th><th>ชื่อรอบ</th><th>วันที่ตรวจนับ</th><th>ผู้สร้าง</th><th>จำนวนครั้งที่นับ</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody>{stockCounts.map(item=><tr key={item.id}><td><b>{item.documentNo}</b></td><td>{item.name}</td><td>{item.countDate}</td><td>{item.createdBy}</td><td>{item.lines.length}</td><td><span className={`count-doc-status ${item.status.toLowerCase()}`}>{item.status==='OPEN'?'กำลังนับ':'เสร็จสิ้น'}</span></td><td><div className="count-history-actions">{item.status==='OPEN'&&<button className="btn secondary" onClick={()=>openSession(item)}><FolderOpen/> เข้าไปนับ</button>}<button className="icon-btn" onClick={()=>setHistoryId(item.id)} title="ดูรายละเอียด"><Eye/></button><button className="icon-btn danger" onClick={()=>setDeleteId(item.id)} title="ลบเอกสาร"><Trash2/></button></div></td></tr>)}</tbody></table>{!stockCounts.length&&<Empty/>}</div></div>}{deleteId&&<ConfirmModal title="ยืนยันลบเอกสารนับสต็อก" text={`ต้องการลบ ${stockCounts.find(item=>item.id===deleteId)?.documentNo||''} หรือไม่? ระบบจะลบประวัติเอกสาร แต่จะไม่ย้อนยอด Stock และ Stock Card ที่ปรับไปแล้ว`} onClose={()=>setDeleteId('')} onConfirm={confirmDelete}/>}</>;
  return <><PageHeader title="นับสต็อกสินค้า" subtitle={`${session?.documentNo} · ${session?.name} · วันที่ ${session?.countDate}`} actions={<><button className="btn secondary" onClick={()=>setMode('history')}><FileClock/> ดูประวัติ</button><button className="btn ghost" onClick={closeSession}>จบรอบการนับ</button></>}/><div className="stock-count-layout"><section className="card stock-count-search"><div className="card-title"><div><h2>1. ค้นหาสินค้าในคลัง {session?.warehouseGroup}</h2><p>ระบบแสดงเฉพาะสินค้าตามคลังที่กำหนดไว้ในเอกสาร</p></div><Search/></div><label className="search"><Search size={17}/><input value={search} onChange={event=>{setSearch(event.target.value);setProductId('');setLotDate('')}} placeholder="พิมพ์ชื่อหรือรหัสสินค้า"/></label><div className="stock-count-results">{matches.map(item=><button key={item.id} className={item.id===productId?'active':''} onClick={()=>chooseProduct(item)}><b>{item.productName}</b><span>{item.productCode} · {item.warehouseGroup} · คงเหลือ {fmt(item.currentStock)} {item.unit}</span></button>)}{!matches.length&&<Empty/>}</div></section><section className="card stock-count-form"><div className="card-title"><div><h2>2. ระบุ Lot และจำนวนที่นับได้</h2><p>สามารถบันทึกจำนวนเดิมซ้ำได้</p></div><ClipboardCheck/></div>{product?<><div className="count-product"><small>สินค้าที่เลือก</small><b>{product.productName}</b><span>{product.productCode} · {product.warehouseGroup} · {product.unit}</span></div><label>Lot (วันที่)<input type="date" value={lotDate} onChange={event=>chooseDate(event.target.value)}/></label>{lotDate&&!lotExists&&<div className="stock-count-warning"><TriangleAlert/><div><b>ไม่พบ Lot นี้ใน Stock</b><span>ยังสามารถระบุจำนวนและยืนยันเพื่อนับ Lot นี้เข้าระบบได้</span></div></div>}{lotDate&&lotExists&&<div className="lot-match"><b>พบ Lot ใน Stock {matchedLots.length} รายการ</b><span>ยอดคงเหลือรวม {fmt(systemQuantity)} {product.unit}</span></div>}{lotDate&&<><label>จำนวนที่นับได้จริง<div className="count-stepper"><button onClick={()=>setCounted(Math.max(0,counted-1))}><Minus/></button><input type="number" min="0" step="any" value={counted} onChange={event=>setCounted(Math.max(0,+(event.target.value||0)))}/><button onClick={()=>setCounted(counted+1)}><Plus/></button></div></label><div className={`count-difference ${difference===0?'same':difference>0?'plus':'minus'}`}><span>ผลต่างจากยอดในระบบ</span><b>{difference>0?'+':''}{fmt(difference)} {product.unit}</b></div><button className="btn primary confirm-count" onClick={()=>setConfirm(true)}><ClipboardCheck/> บันทึกผลตรวจนับ</button></>}</>:<div className="stock-count-placeholder"><ClipboardCheck/><b>กรุณาเลือกสินค้า</b><span>เลือกสินค้าจากด้านซ้ายเพื่อเริ่มนับสต็อก</span></div>}</section></div>{confirm&&<ConfirmModal title="ยืนยันบันทึกผลตรวจนับ" text={`เอกสาร ${session?.documentNo} · Lot ${lotDate}: ยอดระบบ ${fmt(systemQuantity)} → นับได้ ${fmt(counted)} ${product?.unit}`} onClose={()=>setConfirm(false)} onConfirm={submit}/>}</>;
}

function HistoryDetail({document,onBack}){return <div className="card"><div className="card-title"><div><button className="link-btn" onClick={onBack}><ArrowLeft/> รายการเอกสาร</button><h2>{document.documentNo} · {document.name}</h2><p>วันที่ {document.countDate} · ผู้สร้าง {document.createdBy}</p></div><span className={`count-doc-status ${document.status.toLowerCase()}`}>{document.status==='OPEN'?'กำลังนับ':'เสร็จสิ้น'}</span></div><div className="table-wrap"><table><thead><tr><th>วันที่ / เวลา</th><th>รหัสสินค้า</th><th>ชื่อสินค้า</th><th>คลัง</th><th>Lot</th><th>พบ Lot</th><th>ยอดระบบ</th><th>จำนวนที่นับ</th><th>ผลต่าง</th><th>ผู้ตรวจนับ</th></tr></thead><tbody>{document.lines.map(line=><tr key={line.id}><td>{line.countedAt.slice(0,10)}<small>{new Date(line.countedAt).toLocaleTimeString('th-TH')}</small></td><td>{line.productCode}</td><td>{line.productName}</td><td>{line.warehouseGroup}</td><td>{line.lotNo}</td><td>{line.lotFound?'พบ':'Lot ใหม่'}</td><td>{fmt(line.systemQuantity)} {line.unit}</td><td><b>{fmt(line.countedQuantity)} {line.unit}</b></td><td className={line.difference>0?'qty-in':line.difference<0?'qty-out':''}>{line.difference>0?'+':''}{fmt(line.difference)}</td><td>{line.countedBy}</td></tr>)}</tbody></table>{!document.lines.length&&<Empty/>}</div></div>}
