import {useMemo,useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {ArrowLeft,Boxes,GripVertical,MapPinned,PackageCheck,PackageMinus,Plus,Save,Settings2,Trash2,TriangleAlert,X} from 'lucide-react';
import {Bar,BarChart,CartesianGrid,Cell,Legend,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {useApp} from '../context/AppContext';
import {movementLabels,warehouseGroups,units} from '../data/constants';
import {convertQuantity,fmt} from '../utils/helpers';
import {PageHeader,Modal} from '../components/common';
import PowerPointExport from '../components/PowerPointExport';
import './warehouseEnhancements.css';

const emptyLocation=group=>({warehouseGroup:group||'PK',name:'',capacity:50,unit:'กิโลกรัม'});
export default function StorageMapPage(){
  const {group}=useParams(),navigate=useNavigate(),{products,movements,storageLocations,lots,assignProductLocation,unassignProductLocation,saveStorageLocation,reorderStorageLocations,removeStorageLocation}=useApp();
  const showAll=group==='all',warehouse=showAll?null:(warehouseGroups.find(item=>item.path===group)||warehouseGroups.find(item=>item.id===group)||warehouseGroups[0]);
  const locations=showAll?storageLocations:storageLocations.filter(item=>item.warehouseGroup===warehouse.id);
  const usage=useMemo(()=>Object.fromEntries(locations.map(location=>[location.id,lots.filter(lot=>lot.locationId===location.id&&lot.quantityRemaining>0).reduce((sum,lot)=>{const product=products.find(item=>item.id===lot.productId);return sum+convertQuantity(lot.quantityRemaining,product?.unit,location.unit)},0)])),[locations,lots,products]);
  const [editing,setEditing]=useState(null),[error,setError]=useState(''),[assignmentError,setAssignmentError]=useState(''),[dragging,setDragging]=useState(''),[draggingProduct,setDraggingProduct]=useState(''),[dragOver,setDragOver]=useState(''),[settingsMode,setSettingsMode]=useState(false),[removalMode,setRemovalMode]=useState(false),[managingLocation,setManagingLocation]=useState(null),[managingSelected,setManagingSelected]=useState([]),[summaryView,setSummaryView]=useState(''),[selectedProducts,setSelectedProducts]=useState(()=>{try{return JSON.parse(sessionStorage.getItem('csp_map_product_selection'))||[]}catch{return[]}});
  const open=location=>{setEditing(location?{...location}:emptyLocation(warehouse?.id));setError('')};
  const submit=()=>{if(!editing.warehouseGroup||!editing.name.trim()||+editing.capacity<=0){setError('กรุณาเลือกคลัง ระบุชื่อจุดเก็บ และลิมิตมากกว่า 0');return}if((usage[editing.id]||0)>+editing.capacity){setError(`ลิมิตต้องไม่น้อยกว่ายอดที่เก็บอยู่ ${fmt(usage[editing.id])} ${editing.unit}`);return}saveStorageLocation(editing);setEditing(null)};
  const remove=()=>{try{removeStorageLocation(editing.id);setEditing(null)}catch(removeError){setError(removeError.message)}};
  const drop=targetId=>{if(dragging&&dragging!==targetId)reorderStorageLocations(dragging,targetId);setDragging('');setDragOver('')};
  const removeSelectedProduct=id=>{const next=selectedProducts.filter(item=>item!==id);setSelectedProducts(next);sessionStorage.setItem('csp_map_product_selection',JSON.stringify(next))};
  const assignProduct=location=>{const product=products.find(item=>item.id===draggingProduct);if(!product)return;try{assignProductLocation(product.id,location.id);removeSelectedProduct(product.id);setAssignmentError('')}catch(assignError){setAssignmentError(assignError.message)}finally{setDraggingProduct('');setDragOver('')}};
  const assignSelectedProducts=location=>{const selected=products.filter(product=>selectedProducts.includes(product.id)&&product.warehouseGroup===location.warehouseGroup);try{if(!selected.length)throw new Error(`ไม่มีสินค้าคลัง ${location.warehouseGroup} ในรายการที่เลือก`);const selectedIds=new Set(selected.map(product=>product.id)),otherUsage=lots.filter(lot=>lot.locationId===location.id&&!selectedIds.has(lot.productId)&&Number(lot.quantityRemaining)>0).reduce((sum,lot)=>{const product=products.find(item=>item.id===lot.productId);return sum+convertQuantity(lot.quantityRemaining,product?.unit,location.unit)},0),selectedUsage=selected.reduce((sum,product)=>sum+convertQuantity(product.currentStock,product.unit,location.unit),0);if(otherUsage+selectedUsage>Number(location.capacity||0))throw new Error(`จุดเก็บ ${location.name} มีพื้นที่ไม่พอ (${fmt(otherUsage+selectedUsage)} / ${fmt(location.capacity)} ${location.unit})`);selected.forEach(product=>assignProductLocation(product.id,location.id));const assignedIds=new Set(selected.map(product=>product.id)),remaining=selectedProducts.filter(id=>!assignedIds.has(id));setSelectedProducts(remaining);if(remaining.length)sessionStorage.setItem('csp_map_product_selection',JSON.stringify(remaining));else sessionStorage.removeItem('csp_map_product_selection');setAssignmentError(remaining.length?`วางสินค้า ${selected.length} รายการแล้ว เหลืออีก ${remaining.length} รายการจากคลังอื่น`:'')}catch(assignError){setAssignmentError(assignError.message)}};
  const openLocationRemoval=location=>{const ids=products.filter(product=>product.defaultLocationId===location.id||lots.some(lot=>lot.productId===product.id&&lot.locationId===location.id&&Number(lot.quantityRemaining)>0)).map(product=>product.id);setManagingLocation(location);setManagingSelected(ids)};
  const selectLocation=location=>settingsMode?open(location):removalMode?openLocationRemoval(location):navigate(`/stock-card?locationId=${encodeURIComponent(location.id)}&location=${encodeURIComponent(location.name)}&group=${encodeURIComponent(location.warehouseGroup)}`);
  const productsAtLocation=managingLocation?products.filter(product=>product.defaultLocationId===managingLocation.id||lots.some(lot=>lot.productId===product.id&&lot.locationId===managingLocation.id&&Number(lot.quantityRemaining)>0)):[];
  const removeProductFromMap=productId=>{unassignProductLocation(productId);setManagingSelected(current=>current.filter(id=>id!==productId));if(productsAtLocation.length<=1)setManagingLocation(null)};
  const removeSelectedFromMap=()=>{const ids=managingSelected.filter(id=>productsAtLocation.some(product=>product.id===id));ids.forEach(unassignProductLocation);setManagingSelected([]);setManagingLocation(null)};
  const allManagingSelected=productsAtLocation.length>0&&productsAtLocation.every(product=>managingSelected.includes(product.id));
  const activeCount=locations.filter(item=>(usage[item.id]||0)>0).length,overCount=locations.filter(item=>(usage[item.id]||0)>=item.capacity).length;
  const summaryLocations=locations.filter(location=>summaryView==='active'?(usage[location.id]||0)>0:summaryView==='over'?(usage[location.id]||0)>=location.capacity:true);
  const usageChart=[{name:'ใช้งาน',value:activeCount,color:'#12a594'},{name:'ว่าง',value:Math.max(0,locations.length-activeCount-overCount),color:'#f5ad12'},{name:'เต็ม / Over Stock',value:overCount,color:'#ef4444'}].filter(item=>item.value>0);
  const warehouseChart=warehouseGroups.map(item=>{const groupLocations=storageLocations.filter(location=>location.warehouseGroup===item.id),quantity=lots.filter(lot=>lot.warehouseGroup===item.id&&Number(lot.quantityRemaining)>0).reduce((sum,lot)=>sum+Number(lot.quantityRemaining||0),0);return{name:item.name.replace(' (ชำแหละ)','').replace(' (แพ็ค)',''),points:groupLocations.length,quantity,color:{PK:'#0d3b70',IN:'#1263b7',RM:'#ff6c13','FG-CUT':'#eba308','FG-PACK':'#0ba49a'}[item.id]}});
  const recentMovements=movements.filter(item=>showAll||item.warehouseGroup===warehouse.id||item.toWarehouse===warehouse.id).slice(0,5);
  const locationCell=location=>{const used=usage[location.id]||0,percent=location.capacity?Math.round(used/location.capacity*100):0,state=percent>100?'over':percent>=90?'full':percent>0?'active':'empty',assignedCount=products.filter(product=>product.defaultLocationId===location.id).length;return <button draggable={settingsMode} type="button" className={`storage-cell ${state} ${settingsMode?'settings-mode':''} ${removalMode?'removal-ready':''} ${selectedProducts.length?'assignment-ready':''} ${dragging===location.id?'dragging':''} ${dragOver===location.id?'drag-over':''}`} key={location.id} onDragStart={event=>{if(!settingsMode){event.preventDefault();return}setDragging(location.id);event.dataTransfer.effectAllowed='move'}} onDragEnter={()=>setDragOver(location.id)} onDragOver={event=>{if(!settingsMode&&!draggingProduct)return;event.preventDefault();event.dataTransfer.dropEffect='move'}} onDrop={event=>{event.preventDefault();draggingProduct?assignProduct(location):settingsMode&&drop(location.id)}} onDragEnd={()=>{setDragging('');setDragOver('')}} onClick={()=>{if(dragging||draggingProduct)return;if(selectedProducts.length){assignSelectedProducts(location);return}selectLocation(location)}}>{settingsMode&&<span className="drag-handle"><GripVertical/></span>}<span className="location-code">{location.name}</span><span className="location-percent">{percent}%</span><span className="capacity-track"><i style={{width:`${Math.min(percent,100)}%`}}/></span><span className="location-usage">{fmt(used)} / {fmt(location.capacity)} {location.unit}</span>{selectedProducts.length>0&&<span className="click-to-assign">คลิกเพื่อวาง {selectedProducts.length} รายการ</span>}{removalMode&&assignedCount>0&&<span className="click-to-remove">คลิกเพื่อเลือกสินค้าที่จะนำออก</span>}{assignedCount>0&&<span className="assigned-products-count">{assignedCount} สินค้า</span>}</button>};
  const zoneTitle={PK:'พื้นที่สินค้า PK',IN:'พื้นที่รับสินค้า (IN)',RM:'พื้นที่วัตถุดิบ (RM)','FG-CUT':'FG (ชำแหละ) สินค้าสำเร็จรูป','FG-PACK':'FG (แพ็ค) สินค้าสำเร็จรูป (แพ็ค)'};
  return <><PageHeader title={`แผนที่จุดเก็บ · ${showAll?'ทุกคลัง':warehouse.name}`} subtitle={settingsMode?'โหมดตั้งค่า: ลากเพื่อจัดตำแหน่ง หรือคลิกช่องเพื่อแก้ไขชื่อ หน่วย และลิมิต':removalMode?'โหมดนำสินค้าออก: คลิก Box แล้วเลือกสินค้าที่ต้องการนำออกจากแผนที่':'คลิกจุดเก็บเพื่อเปิด Stock Card ของตำแหน่งนั้น'} actions={<>{!showAll&&<button className="btn ghost" onClick={()=>navigate(`/warehouse/${warehouse.path}`)}><ArrowLeft/> กลับคลังสินค้า</button>}<button className={`btn ${removalMode?'danger-btn':'ghost'}`} onClick={()=>{setRemovalMode(value=>!value);setSettingsMode(false)}}><PackageMinus/> {removalMode?'ออกจากโหมดนำออก':'นำสินค้าออกจากแผนที่'}</button><button className={`btn ${settingsMode?'warning-btn':'ghost'}`} onClick={()=>{setSettingsMode(value=>!value);setRemovalMode(false)}}><Settings2/> {settingsMode?'ออกจากการตั้งค่า':'ตั้งค่าแผนที่'}</button><button className="btn primary" onClick={()=>open(null)}><Plus/> เพิ่มช่องในแผนที่</button></>}/>
    <div className="map-ppt-action"><PowerPointExport name={`CSP-แผนที่จุดเก็บ-${showAll?'ทุกคลัง':warehouse.id}`}/></div><div className="map-warehouse-tabs"><button className={showAll?'active':''} onClick={()=>navigate('/warehouse-map/all')}><Boxes/>ทุกคลัง<small>{storageLocations.length} จุด</small></button>{warehouseGroups.map(item=><button key={item.id} className={item.id===warehouse?.id?'active':''} onClick={()=>navigate(`/warehouse-map/${item.path}`)}><MapPinned/>{item.name}<small>{storageLocations.filter(location=>location.warehouseGroup===item.id).length} จุด</small></button>)}</div>
    <div className="map-summary"><button type="button" onClick={()=>setSummaryView('all')}><MapPinned/><span><small>จุดเก็บทั้งหมด</small><b>{locations.length} จุด</b><em>{showAll?'ทุกคลัง':warehouse.name}</em></span></button><button type="button" onClick={()=>setSummaryView('active')}><Boxes/><span><small>ใช้งานอยู่</small><b>{activeCount} จุด</b><em>{locations.length?`${(activeCount/locations.length*100).toFixed(2)}%`:'0%'}</em></span></button><button type="button" onClick={()=>setSummaryView('over')}><TriangleAlert/><span><small>เต็ม / Over Stock</small><b>{overCount} จุด</b><em>{locations.length?`${(overCount/locations.length*100).toFixed(2)}%`:'0%'}</em></span></button></div>
    {assignmentError&&<div className="alert">{assignmentError}</div>}
    {selectedProducts.length>0&&<section className="map-product-tray card"><div><PackageCheck/><span><b>สินค้าที่เลือก {selectedProducts.length} รายการ</b><small>คลิก Box ของคลังเดียวกันเพื่อวางทั้งหมด หรือลากสินค้าแต่ละรายการไปวางแยก Box</small></span></div><div className="map-product-chips">{selectedProducts.map(id=>products.find(product=>product.id===id)).filter(Boolean).map(product=><div draggable key={product.id} onDragStart={event=>{setDraggingProduct(product.id);setAssignmentError('');event.dataTransfer.effectAllowed='move'}} onDragEnd={()=>{setDraggingProduct('');setDragOver('')}}><GripVertical/><span><b>{product.productName}</b><small>{product.productCode} · {product.warehouseGroup}</small></span><button type="button" onClick={()=>removeSelectedProduct(product.id)}><X/></button></div>)}</div></section>}
    <div className={`warehouse-map card warehouse-floorplan ${showAll?'all-warehouses':''}`}>
      <aside className="map-legend"><h3>คำอธิบาย</h3><span><i className="legend-dot active"/>ใช้งานอยู่</span><span><i className="legend-dot empty"/>ว่าง</span><span><i className="legend-dot full"/>เต็ม / Over Stock</span><span><i className="legend-dot disabled"/>ไม่ได้ใช้งาน</span><hr/><h3>การใช้งาน</h3><p>{settingsMode?'ลากช่องเพื่อจัดตำแหน่ง และคลิกเพื่อแก้ไข':removalMode?'คลิก Box เพื่อเลือกสินค้าที่จะนำออก':'คลิกช่องเพื่อเปิด Stock Card'}</p><div className="map-compass"><b>N</b><i>▲</i></div></aside>
      <div className="floorplan-content">{warehouseGroups.filter(item=>showAll||item.id===warehouse.id).map((item,index)=>{const zoneLocations=storageLocations.filter(location=>location.warehouseGroup===item.id);return <section className={`warehouse-zone zone-${item.id.toLowerCase()} ${index===3?'after-aisle':''}`} key={item.id}><header><span>{item.id}</span><b>{zoneTitle[item.id]||item.name}</b></header><div className="zone-grid">{zoneLocations.map(locationCell)}{!zoneLocations.length&&<button type="button" className="storage-cell add-cell" onClick={()=>open(null)}><Plus/><b>เพิ่มจุดเก็บ</b></button>}</div></section>})}<div className="warehouse-aisle horizontal"><span>ทางเดิน</span></div><div className="warehouse-aisle vertical"><span>ทางเดิน</span></div></div>
    </div>
    <div className="map-chart-ppt-action"><PowerPointExport name={`CSP-แผนที่จุดเก็บ-${showAll?'ทุกคลัง':warehouse.id}`}/></div>
    <div className="map-insights compact"><section className="card map-chart-card"><h3>การใช้งานพื้นที่</h3><div className="map-donut"><ResponsiveContainer width="100%" height={155}><PieChart><Pie data={usageChart.length?usageChart:[{name:'ว่าง',value:1,color:'#e2e8f0'}]} dataKey="value" nameKey="name" innerRadius={42} outerRadius={60} paddingAngle={2}>{(usageChart.length?usageChart:[{color:'#e2e8f0'}]).map((item,index)=><Cell key={`${item.color}-${index}`} fill={item.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div><b>{locations.length}</b><span>จุด</span></div></div><div className="map-chart-legend">{usageChart.map(item=><span key={item.name}><i style={{background:item.color}}/>{item.name} <b>{item.value}</b></span>)}</div></section><section className="card map-chart-card"><h3>สรุปจำนวนจุดและปริมาณสินค้าแยกคลัง</h3><ResponsiveContainer width="100%" height={175}><BarChart data={warehouseChart} margin={{top:8,right:4,left:-18,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:9}}/><YAxis yAxisId="points" allowDecimals={false} tick={{fontSize:8}}/><YAxis yAxisId="quantity" orientation="right" tick={{fontSize:8}}/><Tooltip formatter={(value,name)=>[fmt(value),name==='points'?'จำนวนจุด':'ปริมาณสินค้า']}/><Legend formatter={value=>value==='points'?'จำนวนจุด':'ปริมาณสินค้า'}/><Bar yAxisId="points" dataKey="points" name="points" radius={[4,4,0,0]}>{warehouseChart.map(item=><Cell key={item.name} fill={item.color}/>)}</Bar><Bar yAxisId="quantity" dataKey="quantity" name="quantity" fill="#7c3aed" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></section></div>
    <section className="card map-activity"><h3>กิจกรรมล่าสุด</h3><div className="table-wrap"><table><thead><tr><th>เวลา</th><th>รายการ</th><th>คลัง</th><th>ตำแหน่ง</th><th>โดย</th></tr></thead><tbody>{recentMovements.map(item=><tr key={item.id}><td>{item.transactionTime||new Date(item.createdAt||Date.now()).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})}</td><td>{movementLabels[item.transactionType]||item.transactionType}</td><td>{item.warehouseGroup||item.toWarehouse||'—'}</td><td>{item.locationName||'—'}</td><td>{item.createdBy||'Admin'}</td></tr>)}{!recentMovements.length&&<tr><td colSpan="5">ยังไม่มีกิจกรรม</td></tr>}</tbody></table></div></section>
    {editing&&<Modal title={editing.id?`ตั้งค่าจุดเก็บ ${editing.name}`:'เพิ่มช่องในแผนที่'} onClose={()=>setEditing(null)}><div className="storage-form"><label>คลังสินค้า<select value={editing.warehouseGroup} onChange={event=>setEditing({...editing,warehouseGroup:event.target.value})} disabled={Boolean(editing.id)}>{warehouseGroups.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>ชื่อจุดเก็บ<input value={editing.name} onChange={event=>setEditing({...editing,name:event.target.value})} placeholder="เช่น Cold 1, PK-01"/></label><label>ลิมิตสูงสุด<input type="number" min="1" value={editing.capacity} onChange={event=>setEditing({...editing,capacity:event.target.value})}/></label><label>หน่วย<select value={editing.unit} onChange={event=>setEditing({...editing,unit:event.target.value})}>{units.map(unit=><option key={unit}>{unit}</option>)}</select></label>{editing.id&&<div className="storage-current"><span>ปริมาณที่เก็บอยู่</span><b>{fmt(usage[editing.id]||0)} {editing.unit}</b></div>}{error&&<div className="alert full">{error}</div>}</div><div className="modal-actions">{editing.id&&<button className="btn danger-btn" onClick={remove}><Trash2/> ลบจุดเก็บ</button>}<button className="btn ghost" onClick={()=>setEditing(null)}>ยกเลิก</button><button className="btn primary" onClick={submit}><Save/> บันทึก</button></div></Modal>}
    {managingLocation&&<Modal title={`นำสินค้าออกจาก ${managingLocation.name}`} onClose={()=>setManagingLocation(null)} wide><div className="map-remove-products"><p>การนำออกจะไม่ลบสินค้าและ Stock แต่จะล้างข้อมูลตำแหน่งเดิมทั้งหมดและเปลี่ยนเป็น “ยังไม่ระบุจุดจัดเก็บ” รวมถึงรายการเก่าที่คงเหลือ 0</p>{productsAtLocation.length>0&&<div className="map-remove-select-all"><label><input type="checkbox" checked={allManagingSelected} onChange={()=>setManagingSelected(allManagingSelected?[]:productsAtLocation.map(product=>product.id))}/> เลือกทั้งหมด ({productsAtLocation.length} รายการ)</label><span>เลือกแล้ว {managingSelected.filter(id=>productsAtLocation.some(product=>product.id===id)).length} รายการ</span></div>}<div className="map-remove-list">{productsAtLocation.map(product=>{const productLots=lots.filter(lot=>lot.productId===product.id&&lot.locationId===managingLocation.id&&Number(lot.quantityRemaining)>0),quantity=productLots.reduce((sum,lot)=>sum+Number(lot.quantityRemaining||0),0);return <div key={product.id} className={managingSelected.includes(product.id)?'selected':''}><input type="checkbox" checked={managingSelected.includes(product.id)} onChange={()=>setManagingSelected(current=>current.includes(product.id)?current.filter(id=>id!==product.id):[...current,product.id])} aria-label={`เลือก ${product.productName}`}/><span><b>{product.productName}</b><small><strong>รหัส:</strong> {product.productCode||'—'} <i>•</i> <strong>คลัง:</strong> {product.warehouseGroup} <i>•</i> <strong>จุดเก็บ:</strong> {managingLocation.name}</small><small><strong>Lot คงเหลือ:</strong> {productLots.length} Lot <i>•</i> <strong>จำนวน:</strong> {fmt(quantity)} {product.unit||'หน่วย'}{quantity===0&&<em>ข้อมูลตำแหน่งเก่า (ยอด 0)</em>}</small></span><button type="button" className="btn danger-btn" onClick={()=>removeProductFromMap(product.id)}><PackageMinus/> นำออก</button></div>})}{!productsAtLocation.length&&<div className="map-remove-empty">ไม่มีสินค้าอยู่ในจุดเก็บนี้</div>}</div></div><div className="modal-actions"><button className="btn ghost" onClick={()=>setManagingLocation(null)}>ปิด</button><button className="btn danger-btn" disabled={!managingSelected.some(id=>productsAtLocation.some(product=>product.id===id))} onClick={removeSelectedFromMap}><PackageMinus/> นำรายการที่เลือกออก ({managingSelected.filter(id=>productsAtLocation.some(product=>product.id===id)).length})</button></div></Modal>}
    {summaryView&&<Modal title={summaryView==='all'?'รายละเอียดจุดเก็บทั้งหมด':summaryView==='active'?'รายละเอียดจุดเก็บที่ใช้งานอยู่':'รายละเอียดจุดเก็บเต็ม / Over Stock'} onClose={()=>setSummaryView('')} wide><div className="table-wrap"><table><thead><tr><th>จุดเก็บ</th><th>คลัง</th><th>ใช้งาน</th><th>ลิมิต</th><th>สถานะ</th><th>รายละเอียด</th></tr></thead><tbody>{summaryLocations.map(location=>{const used=usage[location.id]||0,over=used>=location.capacity;return <tr key={location.id}><td><b>{location.name}</b></td><td>{location.warehouseGroup}</td><td>{fmt(used)} {location.unit}</td><td>{fmt(location.capacity)} {location.unit}</td><td><span className={`badge ${over?'red':used>0?'green':'orange'}`}>{over?'เต็ม / Over Stock':used>0?'ใช้งานอยู่':'ว่าง'}</span></td><td><button className="btn secondary" onClick={()=>navigate(`/stock-card?locationId=${encodeURIComponent(location.id)}&location=${encodeURIComponent(location.name)}&group=${encodeURIComponent(location.warehouseGroup)}`)}>เปิด Stock Card</button></td></tr>})}</tbody></table>{!summaryLocations.length&&<div className="map-remove-empty">ไม่มีจุดเก็บในสถานะนี้</div>}</div><div className="modal-actions"><button className="btn ghost" onClick={()=>setSummaryView('')}>ปิด</button></div></Modal>}
  </>;
}
